name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    
    - name: Danger checker
      run: |
        curl -sSL https://get.rvm.io | bash -s stable --ruby
        rvm install 2.5.1
        rvm use 2.5.1
        bundle update
        bundle install
        bundle exec danger
