name: Github CI
on:
  pull_request:
    branches:
      - master

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Danger Checker
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      run: |
        bundle update
        bundle install
        bundle exec danger
      
